spring.datasource.url=jdbc:sqlserver://minicore-server-ruales.database.windows.net:1433;database=minicore;user=minicoreAdmin@minicore-server-ruales;password=Minicore123!;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.show-sql=true
spring.jackson.date-format=yyyy-MM-dd
spring.thymeleaf.mode=HTML
